### PR TITLE
support for min/max/avg/stddev

### PR DESCRIPTION
**Pull request by jritsema**
Note that this has not been heavily tested on Windows or different flavors of Linux, so if someone wants to help with that, that would be great.

### CODE REVIEW

**Comment by mondwan** [comment]
Hello,
There are some conflicts on the package.json after merging to others requests.

Can you take a look on that and add your name into the contribution list :D 

Thanks a lot

**Comment by jritsema** [comment]
Hey, yep, I'll take a look.

**Comment by jritsema** [comment]
Hey @mondwan I think I resolved the merge conflicts.  Let me know if this works.

**Comment by mondwan** [comment]
An update about this request.

Current implementation does not work for my Window machine with traditional Chinese language.

After taking a look at the source code, I found that the regex on line 102 does not work if the language is not English.

For example, stdout from a ping command on Chinese window

```
Ping google.com [216.58.203.14] (使用 32 位元組的資料):
回覆自 216.58.203.14: 位元組=32 時間=2ms TTL=54
回覆自 216.58.203.14: 位元組=32 時間=2ms TTL=54
回覆自 216.58.203.14: 位元組=32 時間=3ms TTL=54
回覆自 216.58.203.14: 位元組=32 時間=3ms TTL=54

216.58.203.14 的 Ping 統計資料:
    封包: 已傳送 = 4，已收到 = 4, 已遺失 = 0 (0% 遺失)，
大約的來回時間 (毫秒):
    最小值 = 2ms，最大值 = 3ms，平均 = 2ms

```

Time is named as `時間`.

I will work on that later on.

**Pull request merged**
