### PR TITLE
New option source address

### PR DESCRIPTION
**Pull request by woicha**
Hi guys,
I added a the feature "sourceAddr" (option "-S" for Windows or MacOS, option "-I" for Linux). I tested on a Windows 10 machine. Can anyone test on Linux and MaxOS?
Thanks, Tom

### CODE REVIEW

**Comment by woicha** [comment]
I also had an issue using the "-v6" on my german Windows workstation and added examples.
Have a nice weekend, Tom.

**Comment by mondwan** [comment]
@woicha , I have made serval commits on top of your changes. Please check. I will merge it later on if there are no more problems later

**Comment by woicha** [comment]
@mondwan:
Again many thank's for your prompt reaction. Sorry, I was busy. I successfully tested on my german Windows 10 system. So from my point of view everything is fine to merge with the master branch. 
Maybe someone should test on a Linux (MacOS?) system?

I have just one suggestion: 
What do you think of implementing the following logic?:
If and only if the `sourceAddr` option **is and** the `v6` option **is not** explicitly specified, parse the value of `sourceAddr` if it has IPv6 format and if that is true, set `v6 = true`.

Greetings, Tom.

**Comment by woicha** [comment]
@mondwan:
Hi mondwan,
are there any open issues/problems concerning my changes or would it be possible to merge my commits to master and release a version for npm? 
I'm asking because we want to use the module in our project poductivly and I would prefer to install the module via npm rather then adding the github address of my own master fork to our package.json.

Greetings, Tom.

**Comment by woicha** [comment]
Thanks a lot and there's no reason to be sorry; we are using much more of your work!
So thank **you** for your hard work.

**Comment by danielzzz** [comment]
I just started the project, but there have been so many contributions since then..

**Comment by danielzzz** [comment]
@mondwan can we merge this in?

**Comment by mondwan** [comment]
Hey @woicha , Just back from a busy work.... Sorry about that. For your suggestion, as I don't have much ipv6 devices. I cannot test well that implementation. Maybe you can issue a ticket as one of future extension

Hey @danielzzz , yes we can merge them in :)

**Pull request merged**
