### PR TITLE
Parse IPv6 host & numeric host on Linux

### PR DESCRIPTION
**Pull request by nahanil**
Inspired by #79 

Not sure if I've gone about this the right way, but the odd spacing and bracket placement in Linux with `ping6` meant that 'numeric_host' was never getting set. In a project I'm working on I get odd values for 'host' like `one.one.one.one(2606:4700:4700::1111)`

I wasn't sure how to deal with responses like the following two where the ping command only gives you an IP address or a hostname and not both. In those cases `host` and `numeric_host` will be the same, ie:
```
PING 2606:4700:4700::1111(2606:4700:4700::1111) 56 data bytes
# OR
PING one.one.one.one(one.one.one.one) 56 data bytes
```

I'm tempted to sit on this PR a while and wait for suggestions, as well as try to find a few more machines that I can grab test fixtures from to make sure it does what it should.

**Edit:** Oh yeah! https://travis-ci.org/texh/node-ping. Node >=4 are all passing, lower versions bail on an error with grunt using too-modern JS.

### CODE REVIEW

**Comment by mondwan** [comment]
As we have a config for `v6`, is it better for relying on that value to determine whether it is a ipv4 or not?

**Comment by texh** [comment]
@mondwan Not unless the v6 flag actually works across the board. `/sbin/ping6` won't neccessarily be the place that ping6 is, and calling regular `/bin/ping` could do either of v4 or v6 lookup.

Related to: #69 & https://github.com/danielzzz/node-ping/issues/79#issuecomment-471163331
Debian GNU/Linux 9 (stretch)
```
root@dev:~# /sbin/ping6
-su: /sbin/ping6: No such file or directory
```

```
root@dev:~# which ping6
/bin/ping6
```

**Comment by mondwan** [comment]
@texh Please check whether the implementation works on your platform or not. I will merge this MR soon if there are no more feedback. Thanks

**Comment by texh** [comment]
@mondwan At a glance it looks like it should do the business - will try it out in a few hours and report back :smile:

**Comment by mondwan** [comment]
It sounds there are no problem. I will merge it soon :)

**Pull request merged**
