### PR TITLE
update dependencies + remove warning in test + bump minor version

### PR DESCRIPTION
**Pull request by thib3113**
Hello,

first, I updated devDependencies (because it's always great to be up to date).

I also run tests, and see a warning about a return of a promise, and the promise is never resolved, So I just remove the "return" ( because the catch method already call done() ) .

And finaly, I bump the version, to allow dependents, to update this, an take in account last changes (mainly the #65 ).

### CODE REVIEW

**Comment by mondwan** [comment]
Hi, thanks for ur contribution. In my opinion, the initial test case u edit is not well written. Your fix, however, is not correct. Becoz the `.then` part will be lost and never be caught by mocka

Therefore, either keep the original return but no done or also change the throw line to done(err)

**Comment by thib3113** [comment]
@mondwan I'm not accustomed to chai, so I've done some tests .

>  keep the original return but no done
Don't work, because I've see chai doesn't handle the .catch, only the .then .

And, If I good remember, throwing an Exception in a Promise, will call the catch (and so, the done() ).

So : 
 if the promise work => throw exception => catch to done
 if the promise fail => catch to done

About the test case, I'm not an expert, so I try to modify this the less I can .

**Comment by thib3113** [comment]
I've updated to use done with `done(new Error("error"))`

**Comment by mondwan** [comment]
Ahhh, you are correct. I forgot the behavior of throwing an error :D

Thanks for the contribution again.

在 2018年7月10日週二 18:15，thibaut severac <notifications@github.com> 寫道：

**Pull request merged**
