### PR TITLE
Add Mac OS X to promises and FreeBSD to both

### PR DESCRIPTION
**Pull request by dougluce**
This makes both examples work under OS X and FreeBSD.

### CODE REVIEW

**Comment by Eden-Sun** [comment]
+1
It is a nice work.

**Comment by dougluce** [comment]
@danielzzz need any help with managing issues or pull requests?

**Comment by danielzzz** [comment]
@dougluce I would really appreciate it! I am heavily overloaded with other work. is it possible to add admin rights to other users to the project? I could make you admin of this one if you feel like take it over a bit. (even if it's just temporary)

thanks, dan

**Comment by mondwan** [comment]
If you do not mind, I would also like to help on managing issues or pull requests. :)

**Comment by dougluce** [comment]
Hi Dan,

You should be able to add me as a collaborator to the repo via the 
Settings tab for the repo. I'll be happy to try and get through the 
current backlog, please let me know if you've particular standards you'd 
like to adhere to.

Doug

**Comment by danielzzz** [comment]
ok, @dougluce and @mondwan, I have added you as collaborators. hope it helps unclog this project a bit. thanks!

**Comment by danielzzz** [comment]
drop me a msg to push the lib to npm once ready

**Comment by Eden-Sun** [comment]
this might close #34 ?

**Comment by mondwan** [comment]
Not sure. Although patches come from me, I need time to review what I have written.

Hopefully, I will rewrite a bit such that it can merge harmonically .

**Pull request merged**
