### PR TITLE
Support for non-standard Windows installation directories

### PR DESCRIPTION
**Pull request by andrewf403**
Lookup Windows dir in environment variables

### CODE REVIEW

**Comment by dougluce** [comment]
Hi @andrewf403 -- can you rebase this to master and resolve the conflicts?

**Comment by andrewf403** [comment]
@dougluce sure, done

**Comment by dougluce** [comment]
Hi @andrewf403 -- the history on this looks a little odd. Can you do this from your master branch to clean it up?

    git reset --hard 3f153a2
    git cherry-pick c44223f1

Then re-push (you'll have to force it) and it should be good.

**Comment by andrewf403** [comment]
@dougluce should be ok now

**Comment by dougluce** [comment]
Cool, looks good!

**Pull request merged**
